### ISSUE TITLE
Metadata replication/backup

### ISSUE THREAD

**Issue by iwanbk** [gigforks/minio#18]
We currently use simple file based metadata which will lost in case of corrupted FS.

Need to find a way to provide replication/backup

**Comment by zaibon** [comment]
Since for now the metadata is just file based, we can use a backup tool like [restic](https://github.com/restic/restic) to periodically create a backup of the metadata directory.

That would be driven by the 0-robot who would take care of doing the backup.

The should give us a little security and time to have a proper meta stor and migrate the file metadata to use the meta stor.

**Comment by iwanbk** [comment]
closed in favour of  #34
